services:
  postgres-db:
    container_name: widget
    image: postgres
    restart: always
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: widget_dev
      POSTGRES_PASSWORD: widget_dev12
      POSTGRES_DB: widget
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5434:5432"

volumes:
  postgresql_data:

